"""Add queue entry table

Revision ID: 4fbd8e9265aa
Revises: 
Create Date: 2025-06-12 03:51:09.353074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbd8e9265aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_entry')
    op.create_table(
        'queue_entry',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('office_id', sa.Integer, sa.ForeignKey('office.id'), nullable=False),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('user.id'), nullable=False),
        sa.Column('joined_at', sa.DateTime, nullable=True),
        sa.Column('active', sa.Boolean, nullable=True),
    )
    # ### end Alembic commands ###
